stages:
  - install
  - lint
  - build
  - deploy

install:
  image: node:22.17.0
  stage: install
  artifacts:
    untracked: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  only:
    - dev
    - main
  script:
    - npm install

lint:
  image: node:22.17.0
  stage: lint
  artifacts:
    untracked: true
  dependencies:
    - install
  only:
    - dev
    - main
  script:
    - yarn lint --max-warnings=0

build:development:
  image: node:22.17.0
  stage: build
  artifacts:
    untracked: true
  dependencies:
    - install
    - lint
  only:
    - dev
  script:
    - mv .env.dev .env
    - npm run build-dev

build:production:
  image: node:22.17.0
  stage: build
  artifacts:
    untracked: true
  dependencies:
    - install
    - lint
  only:
    - main
  script:
    - mv .env.prod .env
    - npm run build

.base-deploy:
  stage: deploy
  image: docker:stable
  script:
    - echo "Deploying application..."
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> private.key
    - chmod 600 private.key
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete -e "ssh -i private.key" dist/ $URL:/var/www/safu-launcher
    - echo "Application successfully deployed."

deploy:development:
  extends: .base-deploy
  dependencies:
    - install
    - lint
    - build:development
  environment:
    name: development
    url: https://dev.a.bot
  only:
    - dev

deploy:production:
  extends: .base-deploy
  dependencies:
    - install
    - lint
    - build:production
  environment:
    name: production
    url: https://a.bot
  only:
    - main
